server:
  port: 8080

spring:
  application:
    name: frontend-service
  thymeleaf:
    cache: false

services:
  student-url: ${STUDENT_SERVICE_URL:http://localhost:8081}
  room-url: ${ROOM_SERVICE_URL:http://localhost:8082}
  booking-url: ${BOOKING_SERVICE_URL:http://localhost:8083}
  notification-url: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
